name: Deploy to EC2 (build on EC2)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # Create project folder if missing, else go into it
            if [ ! -d "/home/ubuntu/my-fastapi-app" ]; then
              git clone https://github.com/${{ github.repository }}.git /home/ubuntu/my-fastapi-app
            fi

            cd /home/ubuntu/my-fastapi-app

            # Pull latest from staging
            git fetch origin staging
            git reset --hard origin/staging

            # Stop and rebuild container
            docker stop myapp || true
            docker rm myapp || true
            docker build -t my-fastapi-app:staging .
            docker run -d --name myapp -p 8000:8000 my-fastapi-app:staging
